#!/bin/bash

set -eux

LOGFILE=~/.instack/install-undercloud.log

mkdir -p ~/.instack

exec > >(tee $LOGFILE)
exec 2>&1

# As always...
sudo setenforce 0
sudo -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config

# Enable icehouse rpm's repo
sudo yum -y update http://repos.fedorapeople.org/repos/openstack/openstack-icehouse/rdo-release-icehouse-1.noarch.rpm

sudo yum -y install python-pip

# Workaround for:
# https://bugzilla.redhat.com/show_bug.cgi?id=1061045
# Go ahead and install mariadb-server, and remove the logfile with wrong
# permissions.
sudo yum -y update mariadb-server
sudo rm -f /var/log/mariadb/mariadb.log

pushd instack
sudo pip install -e .
popd

# Upstream dib is fine
if [ ! -d diskimage-builder ]; then
  git clone https://git.openstack.org/openstack/diskimage-builder
  pushd diskimage-builder
  sudo pip install -e .
  popd
fi

# We need the undercloud-stack-config branch of tie
if [ ! -d tripleo-image-elements ]; then
  git clone https://github.com/slagle/tripleo-image-elements
  pushd tripleo-image-elements
  git checkout undercloud-stack-config
  popd
fi

# Clean up from any previous runs...
# TODO: figure out if we want upstream patches for this along the lines of a
# "cleanup" element that cleans up the environment at the very beginning of a
# run.
sudo rm -rf \
  /var/lib/use-ephemeral \
  /etc/neutron/plugin.ini \
  /opt/stack \
  /usr/local/bin/* \
  /mnt/state

export DIB_REPOTYPE_nova=package
export DIB_REPOTYPE_heat=package
export DIB_REPOTYPE_keystone=package
export DIB_REPOTYPE_neutron=package
export DIB_REPOTYPE_glance=package
export DIB_REPOTYPE_swift=package
export DIB_REPOTYPE_python_cinderclient=package
export DIB_REPOTYPE_python_glanceclient=package
export DIB_REPOTYPE_python_heatclient=package
export DIB_REPOTYPE_python_keystoneclient=package
export DIB_REPOTYPE_python_neutronclient=package
export DIB_REPOTYPE_python_novaclient=package
export DIB_REPOTYPE_python_swiftclient=package
export DIB_REPOTYPE_python_ceilometerclient=package

export DIB_REPOTYPE_os_collect_config=tar
export DIB_REPOLOCATION_os_collect_config=http://tarballs.openstack.org/os-collect-config/os-collect-config-0.1.10.tar.gz
export DIB_REPOTYPE_os_refresh_config=tar
export DIB_REPOLOCATION_os_refresh_config=http://tarballs.openstack.org/os-refresh-config/os-refresh-config-0.0.7.tar.gz
export DIB_REPOTYPE_os_apply_config=tar
export DIB_REPOLOCATION_os_apply_config=http://tarballs.openstack.org/os-apply-config/os-apply-config-0.1.11.tar.gz

sudo -E instack \
  -p diskimage-builder/elements/ tripleo-image-elements/elements/ \
  -j instack/json-files/fedora-20-undercloud.json
